### ISSUE TITLE
Problems with drush for drupal8 

### ISSUE THREAD

**Issue by justin-07** [wodby/docker4drupal#108]
after run ` docker-compose exec --user 82 php drush dl _some_module_`
we have this:
```
simplexml_load_file(): I/O warning : failed to load external entity "" Project.php:74  [warning]
Failed to get available update data from https://updates.drupal.org/release-history/ _some_module_/8.x  [error]
Could not download requested project(s).
```

**Comment by Paulmicha** [comment]
After reading [this article by Marc Drummond](https://www.marcdrummond.com/posts/2016/08/18/composer-drupal-8), I became convinced to always use the [Composer template for Drupal projects](https://github.com/drupal-composer/drupal-project) for every Drupal 8 project.

If you'd like something more "flat", here's [Deeson's quickstart template](https://github.com/teamdeeson/d8-quickstart) - see the [presentation blog post](https://www.deeson.co.uk/labs/getting-started-drupal-8-and-composer).

In docker4drupal, contrib modules management would then look like this :

- Download new contrib module : `composer require drupal/adminimal_admin_toolbar`
- Enable contrib module : `drush en adminimal_admin_toolbar -y`

Note: `drush` is an alias that needs to be defined like `alias drush="docker-compose exec --user 82 php drush --root=/var/www/html/web"`

**Comment by csandanov** [comment]
@justin-07 what tag of drupal-php are you using? I was able to download a module via drush like that:
```bash
$ docker run -d wodby/drupal:8-7.1
$ docker exec --user 82 [ID] drush dl devel --root=/var/www/html/web
```

note: wodby/drupal is drupal-php with Drupal core inside installed via composer template.

**Comment by Paulmicha** [comment]
You shouldn't (and normally, can't) download modules with `drush` when using Composer.

Attempting to run e.g. `drush dl solr_devel` should give you this error :
```
This codebase is assembled with Composer instead of Drush. Use `composer update` and `composer require` instead of `drush pm-updatecode` and `drush pm-download`. You may override this error by using the --pm-force option.
```

**Comment by csandanov** [comment]
Well, I agree that it's preferable to download modules via composer when the project itself based on composer template but I was able to download module as shown above – go ahead and try it yourself.

**Comment by Paulmicha** [comment]
→ Then there's something wrong with the setup.

**Comment by RobLoach** [comment]
I've used the following....

```
docker-compose run -w /var/www/html/web php drush status
```

**Comment by csandanov** [comment]
Closing this issue due to no response from the poster

**Comment by grocc** [comment]
Hello, I open this topic again :)
I have problem on installing modules with composer. Here what I've done...
`docker container ls` give me my container id, _r-D8Devel-php-1-96ee6b14_
`docker exec --user 82 -it r-D8Devel-php-1-96ee6b14 bash` log me in on the right container

now, if i run `composer require drupal/adminimal_admin_toolbar` i have the follow result

`bash-4.3$ composer require drupal/adminimal_admin_toolbar
    1/2:	https://packages.drupal.org/8/drupal/provider-2017-4$68b37340bb1544e20e43327a9b3c7af12963d02dc34fee273f0b0f38668a78cd.json
    2/2:	https://packages.drupal.org/8/drupal/provider-2017-3$718bbbeee5427870a3149fd9ca15a9f6a0877c4cb0432e6372fd175d757f8550.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/3:	http://packagist.org/p/provider-latest$a9c00cbcbdad6fc9703777aee2f85d9c0beb6a2ccb95115a323f0f1732c0ad55.json
    2/3:	http://packagist.org/p/provider-2017-07$3360a75c99ee26e0ac28d48503e3fe672f664689e9fd5df647921de207585eff.json
    3/3:	http://packagist.org/p/provider-2017-10$f1a9412881055c197e1eaa2eea993e457bf8a3ddea431170d10d0cfb2834a47b.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Using version ^1.5 for drupal/adminimal_admin_toolbar
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals

Installation failed, reverting ./composer.json to its original content.

                                                                              
  [RuntimeException]                                                          
  web/modules/contrib/admin_toolbar does not exist and could not be created.                                                             
`

checking the permission of the folder i have
drwxr-xr-x    7 www-data www-data      4096 Oct 10 08:40 web
drwxr-xr-x    2 root     1001          4096 Oct 10 08:40 web/modules

so i think that the problem is because i'm logged in as www-data and i want to install something in a folder that i can't manage...
Any idea to solve it?
Thanks!
