### ISSUE TITLE
Would it be possible to symlink the codebase?

### ISSUE THREAD

**Issue by fede-green** [wodby/docker4drupal#242]
### Codebase
mounted codebase

Hello, 

i tried to mount a symlinked codebase this way: 

```
    volumes:
      - ./drupal_root:/var/www/html
```

**drupal_root** being a symlink let's say to ~/projects/myproject. my php and nginx docker environments complained they could not find of course ~/projects/myproject. So i wonder... would it somehow be possible to make it work?

thanks a lot, 

federico

**Comment by jasonruyle** [comment]
I'm not sure D8 supports symbolic links. I ran into issues with trying to symlink modules/themes and it didn't work. In my composer file I ended up having to copy files (instead of symlink).
Easiest test is to run against the ~/projects/myproject folder and not symlink folder. Again, I wasn't successful symlinking modules/themes.

**Comment by szeidler** [comment]
As far as I know is docker not supporting symlinks out of its own context. See https://github.com/moby/moby/issues/1676#issuecomment-23878459
