### ISSUE TITLE
support for third party scripts

### ISSUE THREAD

**Issue by readingdan** [wodby/docker4drupal#255]
### Codebase
Built-in vanilla Drupal or mounted codebase
  
### Host OS 
e.g. macOS Sierra

### Docker info output
```
# Run "docker info" on the host machine and paste output here 
```

### Docker compose file
```yml
# Content of your docker-compose.yml file. Make sure you remove all sensible information you might have there.
```

### Logs output
```
# Run "docker-compose logs [service]". Let's say you get 500 error for some reason then it'll be helpful to provide logs for php and http server (nginx/apache) services.
```

I would like to instal a third party script similar to:

https://github.com/tjko/jpegoptim

What is the correct way to include this in the docker-compose yaml config?

**Comment by csandanov** [comment]
You can install it from alpine repository:
```
sudo apk add --update jpegoptim
```

**Comment by readingdan** [comment]
Thanks, yes logging in with:

docker-compose exec --user root php sh

and executing 

sudo apk add --update jpegoptim

works. 

I was really wondering if there was a way to put this in the docker-compose.yaml so this persists when starting/stopping docker etc

**Comment by csandanov** [comment]
Works fine with [5.x](https://github.com/wodby/docker4drupal/releases/tag/5.0.0) version image:
```
$ docker run --rm -ti wodby/php:5.6-dev-4.2.2 sh                                                                              [16:04:51]
/var/www/html $ sudo apk add --update jpegoptim
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/1) Installing jpegoptim (1.4.4-r0)
Executing busybox-1.27.2-r7.trigger
OK: 192 MiB in 126 packages
```

> I was really wondering if there was a way to put this in the docker-compose.yaml so this persists when starting/stopping docker etc?

the only way to make it persistent is to include it in the image, you can build your own based on ours. 

although It's a very light tool and including it in the basic image won't be a big deal, I'm not sure it's that popular, personally, I never heard of anyone using it until now. Also, I see that it's not actively maintained, the latest release [dated 2016](https://github.com/tjko/jpegoptim/releases), perhaps there are good alternatives you just don't know about, for example [`jpegtran`](https://stackoverflow.com/a/986642/1826109) that comes with libjpeg and already in the image

**Comment by readingdan** [comment]
Thanks for your answer.

Interesting how you are using docker run. Not sure what the -ti flag does?

Yep, I will look into forking yours. In this instance it is supporting something that has been set up on. legacy project. I guess this happens quite a lot.

It's a shame there is no way to include this in the docker-compose file as forking seems like a lot of work just to include these requirements,

**Comment by szeidler** [comment]
Hi @csandanov,
we had a couple of internal discussions about using tools like jpegoptim and co with Docker4Drupal/Wodby. The reason is, that clients often ask us about the Google Pagespeed Insights scores, which we always loose some points, because images could have been compressed better (not speaking about the jpeg quality). Using ImageMagick and strip the image metadata reduced the files quite a lot, but those specialized tools seems to bring better results.

**Comment by csandanov** [comment]
@szeidler we can add `jpegoptim`, it's not a big deal since it's really light. As for the google pagespeed score, we're aware of this need and we want to add mod_pagespeed module to nginx for a while now but it didn't compile on alpine until recently. So, you can expect this in the upcoming updates. Although I'm not 100% sure this module will resolve all compressions issues.

**Comment by csandanov** [comment]
`jpegoptim` has been added in [5.0.3](https://github.com/wodby/docker4drupal/releases/tag/5.0.3)
