### ISSUE TITLE
How to add pthread extension to php container

### ISSUE THREAD

**Issue by robertoperuzzo** [wodby/docker4drupal#275]
Hi there,

I'm bogged down with php extensions. I need to add _pthread_ extension to my drupal application. I was wondering if I'll have to write my custom _Dockerfile_ from scratch or I'll can extend the _wodby/drupal-php_ or add some configurations to docker-compose.yml file.

Thanks.

**Comment by csandanov** [comment]
We don't add pthreads extension to wodby/php image because it requires php to be compiled with the flag `--enable-maintainer-zts` which can cause can cause [significant and asymmetrical slowdowns](http://www.phpinternalsbook.com/build_system/building_php.html). So, you'll have to fork [wodby/base-php](http://github.com/wodby/base-php) (which is already a fork of [_/php](https://github.com/docker-library/php)) to compile with this flag, then fork wodby/php where you add the extension via pecl.
