### ISSUE TITLE
Access to custom .php file

### ISSUE THREAD

**Issue by arrubiu** [wodby/docker4drupal#317]
I've to add on my site some custom .php files, like view.php (for seo reasons).

If I try to add it and to open it in a browser, nginx return me a 404 error.
Is there a way to tell nginx to let open some of these files (like update.php)?

It could be useful also to create some nginx redirects..

Thanks,
Sergio

**Comment by mralexho** [comment]
Hi @arrubiu, you can use the `NGINX_SERVER_EXTRA_CONF_FILEPATH` env variable and add your own nginx rules there.

**Comment by arrubiu** [comment]
Yes, this works, thanks!

**Comment by csandanov** [comment]
Yep, we even have an example in docs how to add an extra php endpoint: https://docs.wodby.com/stacks/drupal/containers/#php-endpoints

Other alternatives:
- since [5.1.2](https://github.com/wodby/docker4drupal/releases/tag/5.1.2) you can change `NGINX_VHOST_PRESET` to `php` to use a virtual host for generic php applications
- switch to apache

**Comment by VladSavitsky** [comment]
> Yep, we even have an example in docs how to add an extra php endpoint: https://docs.wodby.com/stacks/drupal/containers/#php-endpoints
> 
> Other alternatives:
> 
> * since [5.1.2](https://github.com/wodby/docker4drupal/releases/tag/5.1.2) you can change `NGINX_VHOST_PRESET` to `php` to use a virtual host for generic php applications
> * switch to apache

Updated link:
https://wodby.com/docs/stacks/drupal/containers/#php-endpoints
