### ISSUE TITLE
How to change a hosts file

### ISSUE THREAD

**Issue by holyorb2** [wodby/docker4drupal#338]
I need to write IP into the PHP container from the Apache container.

My site uses file_get_contents() and I get error => php_network_getaddresses: getaddrinfo failed: name does not resolve,

I added a line to the /ets/hosts file:

`172.18.0.17      my_site.local`

but after restart this entry is deleted.

**Comment by csandanov** [comment]
Not sure what you mean by writing from apache container since there's no php in apache container to run your code. It sounds like you're trying to change hosts file in a container which is not something you should normally do. You should probably start with explaining what you're trying to achieve in the first place, but this is not the correct place for this, for more generic docker-related questions not specific to this repository, you should use stackoverflow.

If I'm wrong and it's somehow related to d4d setup, feel free to reopen.
