### ISSUE TITLE
Add Drush 9

### ISSUE THREAD

**Issue by ivnish** [wodby/docker4drupal#387]
I can't find drush 9 in docker4drupal. Is it exists? Can you add it to docker image?

**Comment by csandanov** [comment]
we add drush 8.x because php images used not only for D8 but also for D7 which isn't supported by drush 9. If you need drush 9.x you should install it within your project via composer (see [drupal-composer](https://github.com/drupal-composer/drupal-project/)). Our php images have drush launcher installed so when you call `drush` it will use your drush 9.x instead of the global 8.x by default

**Comment by ivnish** [comment]
Why is it so problem? You can add drush 9 BOTH drush 8. Needs to use alias **drush8 and drush (9)** or **drush9 and drush (8)**

I can't use project-local drush, because it doesn't work on client's shared hosting. I use global drush there. I try to use my global drush in d4d, but drush status is OK and other commands doesn't work (drush can't connect to DB)

That's why I want drush 9 in d4d. I hope I'm not alone.

**Comment by csandanov** [comment]
composer doesn't support the installation of multiple packages of the same version. Also see http://docs.drush.org/en/master/install/

> Drush 9 only supports one install method. It requires that your Drupal 8 site be built with Composer and Drush be listed as a dependency.

so, in other words, even if we didn't have to support drush 8, we still wouldn't install drush 9 globally
