### ISSUE TITLE
Install npm and gulp

### ISSUE THREAD

**Issue by usmanublox** [wodby/docker4drupal#457]
Hi,

I am working on existing project that was built by https://github.com/droptica/droopler_project and it required npm and gulp to compiled sass easily. Is there any way to install npm and gulp for my existing project?

Your help and guidance would be really appreciated.

Thanks

**Comment by igorbiki** [comment]
You should be able to install npm & gulp, access php container and install those. You'll need to do it everytime container getc created/recreated:

access php container `docker-compose exec php bash`
install npm `sudo apk update && sudo apk install npm`
install gulp globallu `sudo npm install -g gulp`

This is how I do it, maybe there is a better way. Since I do this on few projects, I add those commands to .bashrc file I use in php container, and using one command I do it all.

**Comment by usmanublox** [comment]
Hi @igorbiki it works for me as it uses `apk add` instead of `apt-get install`.
I really appreciate for your help as it saves my time.
