### ISSUE TITLE
Document the SSHD container

### ISSUE THREAD

**Issue by ndobromirov** [wodby/docker4drupal#65]
What is it's use case?
How to configure it?
How to use it?

**Comment by Vacilando** [comment]
See #39. 

Useful e.g. if you work on Windows but want to use PuTTY (instead of PowerShell) to work with the local server in a Linux environment.

Once you log in you can go to /var/www/html to see the root of your site.
* git commands work well
* what unfortunately does NOT work yet is drush

**Comment by csandanov** [comment]
@Vacilando why do you use PuTTY instead of PowerShell? I'm thinking of removing sshd container from the standard set of containers. Normally, if you need a complete replica of PHP container with SSH you should create a new image based on drupal-php and change the entrypoint

**Comment by Vacilando** [comment]
@csandanov, if there's no way to use git and drush from the SSH container then it's useless indeed and you can remove it.

PuTTY provides the standard environment for Windows users to work in Linux. 
* Working with PowerShell is different, therefore less efficient for people used to Linux. 
* Switching between PowerShell and Linux constantly (eg working locally and on the staging or live server) is another downside. 
* We cannot use SuperPuTTY and other useful tools.

Why not simply adding SSH for the PHP container? That would solve things easily. Would the maintenance really become so much more complex?
The argument "separate system = separate container" does not really stand because we see that if SSH is in a separate container it requires senseless amount of work to get it to function the same way.

Cloning PHP is an option - but then it's almost easier to clone the whole setup or use one of the other local dev environments.

It's not just for me. You will win over a lot of people who are wary of using Windows for for local development directly.

The way I see it: once this and #42 are fixed then docker4drupal will be back in competition with more advanced (but Vagrant-based) systems such as dockerizedrupal.com or (special for Drupal developers) drupalvm.com.

**Comment by ndobromirov** [comment]
Thanks!

**Comment by Vacilando** [comment]
Excellent!

Could you please add sshd as a ready-to-be-uncommented option in the default docker-compose.yml (https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml) -- then it will be easier to get it going.

**Comment by Vacilando** [comment]
Bump. Some documentation about how to connect to the php container via ssh would be great in http://docs.docker4drupal.org/en/latest/ and in form of commented lines in docker-compose.yml  

Also, it is not clear whether it is included in all drupal-php images (5.x-2.x.x and 7.x-2.x.x)...?
