### ISSUE TITLE
Access mysql on host

### ISSUE THREAD

**Issue by dcre** [wodby/docker4drupal#81]
Hi. Is it possible for my drupal running on the containers to access a second mysql database on the host?

**Comment by parijke** [comment]
I think so. On port 8001 you can access the phpmyadmin interface and there you can create a second database

**Comment by dcre** [comment]
@parijke i am not sure you understood my question. Thank you though!

I have a mac with a native MYSQL server running.
On this mac i have docker4drupal running.
I have a drupal instance running on the respective container of docker4drupal.
I need this instance to connect to the host's (mac) MYSQL server.

**Comment by PavelPrischepa** [comment]
@dcre the easiest way is to migrate db into the second docker container of mariadb in docker-compose environment.

**Comment by broniusfatv** [comment]
Ok this is a closed topic but I think the original answer sought was never got.  I found it here:
https://stackoverflow.com/a/43011927/742755
Add to the mysql definition in docker-compose.yml, or docker-compose.override.yml as in my example here, a mapping of local port to docker-mysql port:
```
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    ports:
      - 33306:3306
```
I included `environment` and the password bit not because it is required for this (it is not), but because I wanted to demonstrate both how docker-compose.override.yml selectively merges and overrides specific values and where to nest `ports` to make the magic.

hth
-Bronius

**Comment by csandanov** [comment]
Actually, on macOS you can use `host.docker.internal` to access host network

**Comment by broniusfatv** [comment]
> Actually, on macOS you can use `host.docker.internal` to access host network

Well.. I am using host.docker.internal for php debugging, and I do have ```PHP_XDEBUG_REMOTE_HOST: host.docker.internal``` in my docker-compose.yml, but I could never get anything else I tried to work.. 🤷‍♂ This above works for me..
