### ISSUE TITLE
Revert the 1.2.0 method of storing the database.

### ISSUE THREAD

**Issue by mhavelant** [wodby/docker4drupal#83]
Hi!

In 1.3.0, you changed how the database is stored by allowing docker to manage it instead of persisting at a user defined location.
This goes against the docker best practices by making the containers not ephemeral (see: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/containers-should-be-ephemeral). Also this is not only a best practice, docker emphasizes the "don't store data in the containers" everywhere. I also don't see the benefits of this change.

Please, revert the 1.2.0 state, so this is not a problem any longer, or just please explain the reasoning behind making this change!

**Comment by PavelPrischepa** [comment]
Hi @mhavelant,

MariaDB stores data in `/var/lib/mariadb`, which is not just a directory in container but [Docker volume](https://github.com/wodby/drupal-mariadb/blob/master/Dockerfile#L19).
So it's okay to store persistent data in Docker volumes because it's why they were made.

Also, you may read a related issue https://github.com/wodby/docker4drupal/pull/30.

Feel free to ask if you will have questions.

**Comment by csandanov** [comment]
I have returned commented option to use manual volume for MariaDB

**Comment by mhavelant** [comment]
Amazing, thank you, @csandanov !
